### ISSUE TITLE
当前最新版本的欧路词典字体似乎不会生效？

### ISSUE THREAD

**Issue by Dagwbl** [bamboo512/ModernChineseDict#2]
也没有找到设置选项，也不知道之前生效没，但看到README里面的截图是有生效的

**Comment by pampas9000** [comment]
如果确保字体与 css、mdx 文件在同一文件夹，那么你有尝试过 **设置** - **清空缓存**，然后清空后台重新进入欧路词典 App 么？
![IMG_2820](https://user-images.githubusercontent.com/16702370/192962361-c4e13216-d52f-4eab-bba2-b1d306ae9eaf.jpeg)

**Comment by Dagwbl** [comment]
感谢细致的回复，我一开始是直接clone仓库然后缺少字体，安装就手机就好了，windows电脑上好像会被强制替换成微软雅黑
![image](https://user-images.githubusercontent.com/39078825/192969158-591d5437-c63f-4467-a54b-ba344dc8c947.png)

**Comment by pampas9000** [comment]
你的 Windows 版本是不是 Windows 10 1709 或更新，以及 Windows 11？
如果不是的话，你得自己去下载 思源宋体 非可变字体 的版本才行。

**Comment by Dagwbl** [comment]
> 你的 Windows 版本是不是 Windows 10 1709 或更新，以及 Windows 11？
> 如果不是的话，你得自己去下载 思源宋体 非可变字体 的版本才行。

我是windows11 22h2版本

**Comment by pampas9000** [comment]
[现代汉语词典7-[施工现场]20220918](https://forum.freemdict.com/t/topic/12102)

[CSS 样式](https://forum.freemdict.com/t/topic/16055)

不妨试试新的字典文件与 CSS。
字典是由 [MeigenChou](https://forum.freemdict.com/u/MeigenChou) 大佬从 App 抓取的。CSS 是我重新设计的。

在 Windows 的话，可以直接把 CSS 样式帖子里的思源宋体CN 可变字体直接安装到系统再试试。

**Comment by Dagwbl** [comment]
> [现代汉语词典7-[施工现场]20220918](https://forum.freemdict.com/t/topic/12102)
> 
> [CSS 样式](https://forum.freemdict.com/t/topic/16055)
> 
> 不妨试试新的字典文件与 CSS。 字典是由 [MeigenChou](https://forum.freemdict.com/u/MeigenChou) 大佬从 App 抓取的。CSS 是我重新设计的。
> 
> 在 Windows 的话，可以直接把 CSS 样式帖子里的思源宋体CN 可变字体直接安装到系统再试试。

直接换用链接里面的词典吗？这个可以，很好看啊，太强啦
![image](https://user-images.githubusercontent.com/39078825/194564059-60267d44-81b0-4322-bd6a-357d9f9c3714.png)

**Comment by Dagwbl** [comment]
感谢大佬，我暂时没其他问题，关闭这个issue了
